import React from 'react';

export interface ResonanceGlyphProps {
  size?: number;
  className?: string;
  color?: string;
  intensity?: number; // 0 to 1
}

/**
 * REZEL RESONANCE GLYPH LANGUAGE
 * Abstract mathematical vector primitives generated by the AI operating environment.
 * Replaces generic cartoon/illustrated icons with precise computational signatures.
 */

/** CREATE: Generative aperture & expanding crystal geometry */
export const CreateResonanceGlyph: React.FC<ResonanceGlyphProps> = ({
  size = 24,
  className,
  color = 'currentColor',
}) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    className={className}
    aria-hidden="true"
  >
    {/* Expanding crystalline aperture */}
    <path
      d="M12 2L15 9L22 12L15 15L12 22L9 15L2 12L9 9L12 2Z"
      stroke={color}
      strokeWidth="1.2"
      strokeLinejoin="round"
    />
    {/* Internal radiant vertex */}
    <circle cx="12" cy="12" r="2" fill={color} />
    {/* Concentric aperture rays */}
    <line x1="12" y1="5.5" x2="12" y2="7.5" stroke={color} strokeWidth="1" strokeLinecap="round" />
    <line x1="12" y1="16.5" x2="12" y2="18.5" stroke={color} strokeWidth="1" strokeLinecap="round" />
    <line x1="5.5" y1="12" x2="7.5" y2="12" stroke={color} strokeWidth="1" strokeLinecap="round" />
    <line x1="16.5" y1="12" x2="18.5" y2="12" stroke={color} strokeWidth="1" strokeLinecap="round" />
  </svg>
);

/** CONVERSE: Interacting dual harmonic waveform structures */
export const ConverseResonanceGlyph: React.FC<ResonanceGlyphProps> = ({
  size = 24,
  className,
  color = 'currentColor',
}) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    className={className}
    aria-hidden="true"
  >
    {/* Primary harmonic waveform */}
    <path
      d="M3 12C5.5 7 8.5 7 11 12C13.5 17 16.5 17 19 12L21 12"
      stroke={color}
      strokeWidth="1.3"
      strokeLinecap="round"
    />
    {/* Intersecting secondary waveform */}
    <path
      d="M3 12C5.5 17 8.5 17 11 12C13.5 7 16.5 7 19 12L21 12"
      stroke={color}
      strokeWidth="1"
      strokeDasharray="2 3"
      strokeLinecap="round"
      opacity="0.75"
    />
    {/* Acoustic node points */}
    <circle cx="7" cy="12" r="1.2" fill={color} />
    <circle cx="15" cy="12" r="1.2" fill={color} />
  </svg>
);

/** AUTOMATE: Directed execution lattice & forward flux vectors */
export const AutomateResonanceGlyph: React.FC<ResonanceGlyphProps> = ({
  size = 24,
  className,
  color = 'currentColor',
}) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    className={className}
    aria-hidden="true"
  >
    {/* Forward execution track */}
    <line x1="3" y1="12" x2="15" y2="12" stroke={color} strokeWidth="1.2" strokeLinecap="round" />
    <line x1="5" y1="7" x2="13" y2="7" stroke={color} strokeWidth="1" strokeLinecap="round" opacity="0.6" />
    <line x1="5" y1="17" x2="13" y2="17" stroke={color} strokeWidth="1" strokeLinecap="round" opacity="0.6" />
    {/* Execution node chevron */}
    <path
      d="M13 6L19 12L13 18"
      stroke={color}
      strokeWidth="1.4"
      strokeLinecap="round"
      strokeLinejoin="round"
    />
    {/* Process anchor */}
    <circle cx="5" cy="12" r="1.5" fill={color} />
  </svg>
);

/** ANALYZE: Spectral scan strata & signal decomposition curves */
export const AnalyzeResonanceGlyph: React.FC<ResonanceGlyphProps> = ({
  size = 24,
  className,
  color = 'currentColor',
}) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    className={className}
    aria-hidden="true"
  >
    {/* Spectral scan strata lines */}
    <line x1="4" y1="6" x2="20" y2="6" stroke={color} strokeWidth="1" strokeDasharray="1 3" />
    <line x1="4" y1="18" x2="20" y2="18" stroke={color} strokeWidth="1" strokeDasharray="1 3" />
    {/* Analytical curve */}
    <path
      d="M4 15C7 15 8 9 11 9C14 9 15 15 18 15C19.5 15 20 12 20 12"
      stroke={color}
      strokeWidth="1.3"
      strokeLinecap="round"
    />
    {/* Precision sampling points */}
    <circle cx="11" cy="9" r="1.5" fill={color} />
    <circle cx="18" cy="15" r="1.2" fill={color} />
  </svg>
);

/** INSPECT: Nested ocular aperture & layered observation reticle */
export const InspectResonanceGlyph: React.FC<ResonanceGlyphProps> = ({
  size = 24,
  className,
  color = 'currentColor',
}) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    className={className}
    aria-hidden="true"
  >
    {/* Outer observation diamond */}
    <rect
      x="12"
      y="3.5"
      width="12"
      height="12"
      transform="rotate(45 12 3.5)"
      stroke={color}
      strokeWidth="1.1"
    />
    {/* Inner concentric ocular ring */}
    <circle cx="12" cy="12" r="3.5" stroke={color} strokeWidth="1.2" />
    <circle cx="12" cy="12" r="1.2" fill={color} />
    {/* Corner reticle marks */}
    <line x1="12" y1="1" x2="12" y2="3" stroke={color} strokeWidth="1.2" strokeLinecap="round" />
    <line x1="12" y1="21" x2="12" y2="23" stroke={color} strokeWidth="1.2" strokeLinecap="round" />
    <line x1="1" y1="12" x2="3" y2="12" stroke={color} strokeWidth="1.2" strokeLinecap="round" />
    <line x1="21" y1="12" x2="23" y2="12" stroke={color} strokeWidth="1.2" strokeLinecap="round" />
  </svg>
);

/** CONTROL: Governance lattice & orthogonal stabilization braces */
export const ControlResonanceGlyph: React.FC<ResonanceGlyphProps> = ({
  size = 24,
  className,
  color = 'currentColor',
}) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    className={className}
    aria-hidden="true"
  >
    {/* Hexagonal boundary lattice */}
    <path
      d="M12 3L20 7.5V16.5L12 21L4 16.5V7.5L12 3Z"
      stroke={color}
      strokeWidth="1.2"
      strokeLinejoin="round"
    />
    {/* Orthogonal stabilizing tri-axis */}
    <line x1="12" y1="12" x2="12" y2="3.5" stroke={color} strokeWidth="1" strokeLinecap="round" />
    <line x1="12" y1="12" x2="19.5" y2="16" stroke={color} strokeWidth="1" strokeLinecap="round" />
    <line x1="12" y1="12" x2="4.5" y2="16" stroke={color} strokeWidth="1" strokeLinecap="round" />
    {/* Central governance nucleus */}
    <circle cx="12" cy="12" r="1.8" fill={color} />
  </svg>
);
