/**
 * Rezel 11.4A — Safe Built-in Workflow Templates
 *
 * Provides out-of-the-box parameterized templates:
 * 1. blender.city: Procedural city assembly (Road, Buildings, Camera, Verification)
 * 2. ae.motion_graphic: Motion graphic composition (Comp, Header, Subtitle, Hierarchy, Verification)
 * 3. generic.verify: Safe read-only inspection and assertion workflow
 */

import type { WorkflowTemplate } from './types';

export const BUILTIN_BLENDER_CITY_TEMPLATE: WorkflowTemplate = {
  id: 'blender.city',
  version: '1.0.0',
  name: 'Create Blender City Scene',
  description: 'Generates a procedural 3D city scene with roadway, building structures, and camera framing.',
  parameters: [
    {
      name: 'CITY_NAME',
      type: 'string',
      description: 'Unique name identifier for the city scene',
      required: true,
      minLength: 3,
      maxLength: 64,
    },
    {
      name: 'BUILDING_COUNT',
      type: 'number',
      description: 'Number of building structures to construct',
      required: false,
      defaultValue: 4,
      minValue: 1,
      maxValue: 20,
    },
    {
      name: 'STYLE',
      type: 'string',
      description: 'Visual architectural style',
      required: false,
      defaultValue: 'modern',
      allowedValues: ['modern', 'cyberpunk', 'lowpoly', 'brutalist'],
    },
  ],
  requiredApplications: ['blender'],
  requiredCapabilities: [
    'blender.inspect_scene',
    'blender.create_object',
    'blender.create_camera',
    'blender.modify_object',
  ],
  defaultRoutingProfile: 'AUTO',
  metadata: {
    author: 'Rezel Core Systems',
    tags: ['blender', '3d', 'procedural', 'city'],
    category: '3D Automation',
    estimatedDurationSec: 15,
  },
  steps: [
    {
      id: 'step_inspect_initial',
      description: 'Inspect initial Blender scene state',
      toolName: 'blender.inspect_scene',
      toolArgs: {},
      mutatesExternalState: false,
      category: 'SYSTEM',
      risk: 'LOW',
      requiredLocks: [{ uri: 'app:blender', access: 'READ' }],
    },
    {
      id: 'step_create_road',
      description: 'Create main boulevard roadway for {{CITY_NAME}}',
      toolName: 'blender.create_object',
      toolArgs: {
        name: '{{CITY_NAME}}_Roadway',
        type: 'CUBE',
        location: [0, 0, 0],
      },
      dependsOn: ['step_inspect_initial'],
      mutatesExternalState: true,
      category: 'CODING',
      risk: 'HIGH',
      requiredLocks: [{ uri: 'app:blender', access: 'WRITE' }],
      verificationPredicate: {
        operator: 'EXISTS',
        entityName: '{{CITY_NAME}}_Roadway',
        entityType: 'MESH',
      },
    },
    {
      id: 'step_create_tower_a',
      description: 'Create primary building tower',
      toolName: 'blender.create_object',
      toolArgs: {
        name: '{{CITY_NAME}}_Tower_Alpha',
        type: 'CUBE',
        location: [-4, 0, 3],
      },
      dependsOn: ['step_create_road'],
      mutatesExternalState: true,
      category: 'CODING',
      risk: 'HIGH',
      requiredLocks: [{ uri: 'app:blender', access: 'WRITE' }],
      verificationPredicate: {
        operator: 'EXISTS',
        entityName: '{{CITY_NAME}}_Tower_Alpha',
        entityType: 'MESH',
      },
    },
    {
      id: 'step_create_tower_b',
      description: 'Create secondary plaza building',
      toolName: 'blender.create_object',
      toolArgs: {
        name: '{{CITY_NAME}}_Tower_Beta',
        type: 'CUBE',
        location: [4, 0, 2],
      },
      dependsOn: ['step_create_road'],
      mutatesExternalState: true,
      category: 'CODING',
      risk: 'HIGH',
      requiredLocks: [{ uri: 'app:blender', access: 'WRITE' }],
      verificationPredicate: {
        operator: 'EXISTS',
        entityName: '{{CITY_NAME}}_Tower_Beta',
        entityType: 'MESH',
      },
    },
    {
      id: 'step_create_camera',
      description: 'Create framing camera overlooking {{CITY_NAME}}',
      toolName: 'blender.create_camera',
      toolArgs: {
        name: '{{CITY_NAME}}_MainCamera',
        location: [0, -12, 6],
      },
      dependsOn: ['step_create_tower_a', 'step_create_tower_b'],
      mutatesExternalState: true,
      category: 'CODING',
      risk: 'HIGH',
      requiredLocks: [{ uri: 'app:blender', access: 'WRITE' }],
      verificationPredicate: {
        operator: 'EXISTS',
        entityName: '{{CITY_NAME}}_MainCamera',
        entityType: 'CAMERA',
      },
    },
    {
      id: 'step_inspect_final',
      description: 'Inspect scene and verify complete {{CITY_NAME}} construction',
      toolName: 'blender.inspect_scene',
      toolArgs: {},
      dependsOn: ['step_create_camera'],
      mutatesExternalState: false,
      category: 'SYSTEM',
      risk: 'LOW',
      requiredLocks: [{ uri: 'app:blender', access: 'READ' }],
    },
  ],
};

export const BUILTIN_AE_MOTION_GRAPHIC_TEMPLATE: WorkflowTemplate = {
  id: 'ae.motion_graphic',
  version: '1.0.0',
  name: 'Create After Effects Motion Graphic',
  description: 'Creates a stylized title graphic composition in After Effects with layered typography and visual hierarchy.',
  parameters: [
    {
      name: 'TITLE',
      type: 'string',
      description: 'Primary title text string',
      required: true,
      minLength: 1,
      maxLength: 120,
    },
    {
      name: 'SUBTITLE',
      type: 'string',
      description: 'Secondary subtitle text string',
      required: false,
      defaultValue: 'Powered by Rezel OS',
    },
    {
      name: 'WIDTH',
      type: 'number',
      description: 'Composition resolution width in pixels',
      required: false,
      defaultValue: 1920,
      minValue: 640,
      maxValue: 7680,
    },
    {
      name: 'HEIGHT',
      type: 'number',
      description: 'Composition resolution height in pixels',
      required: false,
      defaultValue: 1080,
      minValue: 480,
      maxValue: 4320,
    },
    {
      name: 'FPS',
      type: 'number',
      description: 'Composition framerate',
      required: false,
      defaultValue: 60,
      allowedValues: [24, 25, 30, 60],
    },
    {
      name: 'DURATION',
      type: 'number',
      description: 'Composition duration in seconds',
      required: false,
      defaultValue: 10,
      minValue: 1,
      maxValue: 300,
    },
  ],
  requiredApplications: ['after_effects'],
  requiredCapabilities: [
    'ae_create_project',
    'ae_create_comp',
    'ae_add_text_layer',
    'ae_set_transform',
    'ae_inspect_project',
  ],
  defaultRoutingProfile: 'AUTO',
  metadata: {
    author: 'Rezel Core Systems',
    tags: ['after_effects', 'motion_graphics', 'typography', 'video'],
    category: 'Motion Design',
    estimatedDurationSec: 12,
  },
  steps: [
    {
      id: 'step_ae_clean_proj',
      description: 'Initialize clean After Effects project',
      toolName: 'ae_create_project',
      toolArgs: {},
      mutatesExternalState: true,
      category: 'AUTOMATION',
      risk: 'HIGH',
      requiredLocks: [{ uri: 'app:after_effects', access: 'WRITE' }],
    },
    {
      id: 'step_ae_create_comp',
      description: 'Create composition ({{WIDTH}}x{{HEIGHT}} @ {{FPS}}fps)',
      toolName: 'ae_create_comp',
      toolArgs: {
        name: 'MG_{{TITLE}}',
        width: '{{WIDTH}}',
        height: '{{HEIGHT}}',
        duration: '{{DURATION}}',
        frameRate: '{{FPS}}',
      },
      dependsOn: ['step_ae_clean_proj'],
      mutatesExternalState: true,
      category: 'AUTOMATION',
      risk: 'HIGH',
      requiredLocks: [{ uri: 'app:after_effects', access: 'WRITE' }],
      verificationPredicate: {
        operator: 'EXISTS',
        entityName: 'MG_{{TITLE}}',
        entityType: 'COMPOSITION',
      },
    },
    {
      id: 'step_ae_add_title',
      description: 'Add primary title layer: {{TITLE}}',
      toolName: 'ae_add_text_layer',
      toolArgs: {
        compName: 'MG_{{TITLE}}',
        layerName: 'Header_Title',
        text: '{{TITLE}}',
        fontSize: 64,
      },
      dependsOn: ['step_ae_create_comp'],
      mutatesExternalState: true,
      category: 'AUTOMATION',
      risk: 'HIGH',
      requiredLocks: [{ uri: 'app:after_effects', access: 'WRITE' }],
    },
    {
      id: 'step_ae_add_sub',
      description: 'Add subtitle layer: {{SUBTITLE}}',
      toolName: 'ae_add_text_layer',
      toolArgs: {
        compName: 'MG_{{TITLE}}',
        layerName: 'Subtitle_Description',
        text: '{{SUBTITLE}}',
        fontSize: 32,
      },
      dependsOn: ['step_ae_add_title'],
      mutatesExternalState: true,
      category: 'AUTOMATION',
      risk: 'HIGH',
      requiredLocks: [{ uri: 'app:after_effects', access: 'WRITE' }],
    },
    {
      id: 'step_ae_layout',
      description: 'Set transform layout for hierarchy',
      toolName: 'ae_set_transform',
      toolArgs: {
        compName: 'MG_{{TITLE}}',
        layerName: 'Header_Title',
        position: [960, 480],
        scale: [100, 100],
      },
      dependsOn: ['step_ae_add_sub'],
      mutatesExternalState: true,
      category: 'AUTOMATION',
      risk: 'HIGH',
      requiredLocks: [{ uri: 'app:after_effects', access: 'WRITE' }],
    },
    {
      id: 'step_ae_inspect_final',
      description: 'Inspect After Effects project to verify composition and layers',
      toolName: 'ae_inspect_project',
      toolArgs: {},
      dependsOn: ['step_ae_layout'],
      mutatesExternalState: false,
      category: 'SYSTEM',
      risk: 'LOW',
      requiredLocks: [{ uri: 'app:after_effects', access: 'READ' }],
    },
  ],
};

export const BUILTIN_GENERIC_VERIFY_TEMPLATE: WorkflowTemplate = {
  id: 'generic.verify',
  version: '1.0.0',
  name: 'Generic Inspection and Verification Workflow',
  description: 'Audits application state, evaluates safety invariants, and verifies observable external state.',
  parameters: [
    {
      name: 'TARGET_APP',
      type: 'string',
      description: 'Target application name to audit',
      required: false,
      defaultValue: 'blender',
      allowedValues: ['blender', 'after_effects', 'system'],
    },
    {
      name: 'ENTITY_NAME',
      type: 'string',
      description: 'Expected entity name to verify',
      required: true,
      minLength: 1,
    },
  ],
  requiredCapabilities: ['blender.inspect_scene'],
  defaultRoutingProfile: 'LOCAL',
  metadata: {
    author: 'Rezel Core Systems',
    tags: ['verification', 'audit', 'generic'],
    category: 'Verification',
    estimatedDurationSec: 5,
  },
  steps: [
    {
      id: 'step_audit_pre',
      description: 'Perform initial observation of {{TARGET_APP}} state',
      toolName: 'blender.inspect_scene',
      toolArgs: {},
      mutatesExternalState: false,
      category: 'SYSTEM',
      routingProfile: 'LOCAL',
      risk: 'LOW',
    },
    {
      id: 'step_audit_verify',
      description: 'Verify existence of {{ENTITY_NAME}} in {{TARGET_APP}}',
      toolName: 'blender.inspect_scene',
      toolArgs: {},
      dependsOn: ['step_audit_pre'],
      mutatesExternalState: false,
      category: 'REASONING',
      routingProfile: 'LOCAL',
      risk: 'LOW',
      verificationPredicate: {
        operator: 'EXISTS',
        entityName: '{{ENTITY_NAME}}',
      },
    },
  ],
};

export const BUILTIN_WORKFLOW_TEMPLATES: WorkflowTemplate[] = [
  BUILTIN_BLENDER_CITY_TEMPLATE,
  BUILTIN_AE_MOTION_GRAPHIC_TEMPLATE,
  BUILTIN_GENERIC_VERIFY_TEMPLATE,
];
